---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% if bart_direction and bart_direction != '' and bart_direction != 'Any' %}\r\nhttps://api.bart.gov/api/etd.aspx?cmd=etd&orig={{ bart_origin_station }}&dir={{ bart_direction }}&key=MW9S-E7SL-26DU-VV8V&json=y\r\n{% else %}\r\nhttps://api.bart.gov/api/etd.aspx?cmd=etd&orig={{ bart_origin_station }}&key=MW9S-E7SL-26DU-VV8V&json=y\r\n{% endif %}"
polling_headers: ''
polling_body: ''
id: 180254
custom_fields:
- keyname: bart_origin_station
  field_type: select
  name: BART Origin Station
  description: Where you're boarding
  required: true
  options:
  - 12th Street Oakland: 12TH
  - 16th Street Mission: 16TH
  - 19th Street Oakland: 19TH
  - 24th Street Mission: 24TH
  - Antioch: ANTC
  - Ashby: ASHB
  - Balboa Park: BALB
  - Bay Fair: BAYF
  - Berryessa / North San Jose: BERY
  - Castro Valley: CAST
  - Civic Center / UN Plaza: CIVC
  - Coliseum: COLS
  - Colma: COLM
  - Concord: CONC
  - Daly City: DALY
  - Downtown Berkeley: DBRK
  - Dublin / Pleasanton: DUBL
  - El Cerrito del Norte: DELN
  - El Cerrito Plaza: PLZA
  - Embarcadero: EMBR
  - Fremont: FRMT
  - Fruitvale: FTVL
  - Glen Park: GLEN
  - Hayward: HAYW
  - Lafayette: LAFY
  - Lake Merritt: LAKE
  - MacArthur: MCAR
  - Millbrae: MLBR
  - Milpitas: MLPT
  - Montgomery St.: MONT
  - North Berkeley: NBRK
  - North Concord / Martinez: NCON
  - Oakland International Airport: OAKL
  - Orinda: ORIN
  - Pittsburg / Bay Point: PITT
  - Pittsburg Center: PCTR
  - Pleasant Hill / Contra Costa Centre: PHIL
  - Powell St.: POWL
  - Richmond: RICH
  - Rockridge: ROCK
  - San Bruno: SBRN
  - San Francisco International Airport: SFIA
  - San Leandro: SANL
  - South Hayward: SHAY
  - South San Francisco: SSAN
  - Union City: UCTY
  - Walnut Creek: WCRK
  - Warm Springs / South Fremont: WARM
  - West Dublin / Pleasanton: WDUB
  - West Oakland: WOAK
- keyname: bart_direction
  field_type: select
  name: Direction
  label: Direction (Optional)
  description: Filter trains by direction (leave blank for all directions)
  required: false
  options:
  - ''
  - "n"
  - s
  default: ''
- keyname: bart_train_lines
  field_type: select
  name: Train Line Filter
  label: Train Lines (Optional)
  description: Filter to show only selected train lines (leave blank for all lines)
  required: false
  multiple: true
  options:
  - Richmond: RICH
  - Millbrae: MLBR
  - Dublin/Pleasanton: DUBL
  - Berryessa/North San Jos√©: BERY
  - Daly City: DALY
  - Warm Springs/South Fremont: WARM
  - Antioch: ANTC
  - Pittsburg/Bay Point: PITT
  - SFO International Airport: SFIA
  - Oakland Airport: OAKL
- keyname: badge_visibility
  field_type: select
  name: Badge Visibility
  multiple: true
  required: false
  options:
  - platform
  - bike
  - delay
  - cancel
  - no_badges
  default: platform,bike,delay,cancel
name: FRVL Trmnl
refresh_interval: 30
