---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% if bart_direction and bart_direction != '' and bart_direction != 'Any' %}\r\nhttps://api.bart.gov/api/etd.aspx?cmd=etd&orig={{ bart_origin_station }}&dir={{ bart_direction }}&key=MW9S-E7SL-26DU-VV8V&json=y\r\n{% else %}\r\nhttps://api.bart.gov/api/etd.aspx?cmd=etd&orig={{ bart_origin_station }}&key=MW9S-E7SL-26DU-VV8V&json=y\r\n{% endif %}"
polling_headers: ''
polling_body: ''
id: 180254
custom_fields:
- keyname: bart_origin_station
  field_type: select
  name: BART Origin Station
  description: Where you're boarding
  required: true
  options:
  - 12TH
  - 16TH
  - 19TH
  - 24TH
  - ANTC
  - ASHB
  - BALB
  - BAYF
  - BERY
  - CAST
  - CIVC
  - COLM
  - COLS
  - CONC
  - DALY
  - DBRK
  - DELN
  - DUBL
  - EMBR
  - FRMT
  - FTVL
  - GLEN
  - HAYW
  - LAFY
  - LAKE
  - MCAR
  - MLBR
  - MLPT
  - MONT
  - NBRK
  - NCON
  - OAKL
  - ORIN
  - PCTR
  - PHIL
  - PITT
  - PLZA
  - POWL
  - RICH
  - ROCK
  - SANL
  - SBRN
  - SFIA
  - SHAY
  - SSAN
  - UCTY
  - WARM
  - WCRK
  - WDUB
  - WOAK
- keyname: bart_direction
  field_type: select
  name: Direction
  label: Direction (Optional)
  description: Filter trains by direction (leave blank for all directions)
  required: false
  options:
  - ''
  - "n"
  - s
- keyname: bart_destinations
  field_type: multiselect
  name: Destinations
  description: Select which destinations to show (defaults to all)
  required: false
  options:
  - RICH
  - DUBL
  - BERY
  - MLBR
  - ANTC
  - DALY
name: FRVL Trmnl
refresh_interval: 30
