- keyname: bart_origin_station
  field_type: select
  name: BART Origin Station
  description: Where you're boarding
  required: true
  options:
  - 12TH
  - 16TH
  - 19TH
  - 24TH
  - ANTC
  - ASHB
  - BALB
  - BAYF
  - BERY
  - CAST
  - CIVC
  - COLM
  - COLS
  - CONC
  - DALY
  - DBRK
  - DELN
  - DUBL
  - EMBR
  - FRMT
  - FTVL
  - GLEN
  - HAYW
  - LAFY
  - LAKE
  - MCAR
  - MLBR
  - MLPT
  - MONT
  - NBRK
  - NCON
  - OAKL
  - ORIN
  - PCTR
  - PHIL
  - PITT
  - PLZA
  - POWL
  - RICH
  - ROCK
  - SANL
  - SBRN
  - SFIA
  - SHAY
  - SSAN
  - UCTY
  - WARM
  - WCRK
  - WDUB
  - WOAK
- keyname: bart_direction
  field_type: select
  name: Direction
  label: Direction (Optional)
  description: Filter trains by direction (leave blank for all directions)
  required: false
  options:
  - ''
  - n
  - s
  default: ''